app_pdf:
    path: '/pdf'
    controller: 'App\Controller\PdfController::generatePdfForm'

app_generate_pdf:
    path: '/pdf/generate'
    controller: 'App\Controller\PdfController::generatePdf'

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_verify_email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail  

homepage:
    path: /
    controller: App\Controller\HomeController::index

subscription_change:
    path: /subscription/change
    controller: App\Controller\SubscriptionController::changeSubscription

subscription:
    path: /subscription
    controller: App\Controller\Subscription

pdf_generation:
    path: /pdf/generate
    controller: App\Controller\PdfController::generatePdf

history:
    path: /history
    controller: App\Controller\HistoryController::index